### ISSUE TITLE
New voice TTS-1 FR

### ISSUE THREAD

**Issue by stanthewizzard** [matatonic/openedai-speech#35]
Hello

I'm struggling to find out how to add french voices.

What I have done:
```
#!/bin/sh
models=${*:-"fr_FR-tom-medium"} # en_US-ryan-high
piper --update-voices --data-dir voices --download-dir voices --model x 2> /dev/null
for i in $models ; do
    [ ! -e "./$i.onnx" ] && piper --data-dir ./ --download-dir ./ --model $i < /dev/null > /dev/null
done
```

2 files are downloaded (same place as the others)
fr_FR-tom-medium.onnx
fr_FR-tom-medium.onnx.json
(same rights as the other files 0644)

In voice_to_speaker.yaml, I have added

```
tts-1:
  tom:
    model: voices/fr_FR-tom-medium.onnx
    speaker: # default speaker
```

When I'm trying (with openwebui to use a model:
alloy
The name alloy is auto-completed.
model is running.
Voice is ok

tom
The name til is NOT auto-completed.
model is NOT running.
No voice
and nothing in log :0

Thanks for help

**Comment by matatonic** [comment]
Hi, I've been out of the country with limited internet access - has this been resolved? It looks right so far. 

1. tom will not be auto-completed, only the standard names are known to clients and there is now API call to list the voices.

Are you looking at the logs for open-webui? In openedai-speech you can start the server with `--log-level DEBUG` for additional logging. Enable this in `speech.env` with `EXTRA_ARGS=--log-level DEBUG`

It may be sample rate, this voice seems to require `* Samplerate: 44,100Hz` instead of the usual 22050Hz... I may need to update the code if this is the case.

**Comment by stanthewizzard** [comment]
ok
thanks if you can update
would like to use a french voice lol

**Comment by shalchianmh** [comment]
I have the exact same problem, 
I use `fa_IR-gyro-medium.onnx`, and I followed the documentation step by step, but the model is not running.

**Comment by stanthewizzard** [comment]
No issue on the name sadly

**Comment by matatonic** [comment]
Sorry for the delay in any fixes, I've been out of the country with limited internet access for the last month. I'm still getting caught up.

**Comment by shalchianmh** [comment]
> No issue on the name sadly What doc did you follow ?

I just downloaded `fa_IR-gyro-medium.onnx` and `fa_IR-gyro-medium.onnx.json` from piper in huggingface, then I added them to `voices` folder
and I added this to `config/voice_to_speaker.yaml`:
```
tts-1:
.
.
.
  gyro:
    model: voices/fa_IR-gyro-medium.onnx
    speaker: # default speaker
```
and then I ran docker compose
did you try this?

**Comment by stanthewizzard** [comment]
yes 
not working :(
