### ISSUE TITLE
Nvidia GPU RTX: 3060 not being utilized in the docker image

### ISSUE THREAD

**Issue by Prime-AI28** [matatonic/openedai-speech#48]
even though I have a working 3060, with cuda and all set up on my main machine, when I am running a docker using the latest image of opendai-speech, after first time, every timethe system starts in the logs i can see this error/warning:

![image](https://github.com/user-attachments/assets/12f3c4ba-bf99-4741-aeca-e59cbeabbcb7)

and then the model only uses cpu which is very slow, additionally from the exec when i run nvidia-smi:
![image](https://github.com/user-attachments/assets/de97d4e7-6589-4425-ad5e-d0e13a46ec17)

and when i try to see the cuda status in python I am again getting the same error:
![image](https://github.com/user-attachments/assets/df85977e-9745-40ec-a9e0-dcbb040ce066)

**Comment by matatonic** [comment]
Those errors are from inside the running container?

I find that error (device count error) sometimes happens to me when a system component is upgraded (nvidia driver usually) and is fixed with a reboot. I'm not sure if there is a better way.

You're seeing this any time you restart the container? ie. `docker compose restart` causes this?

**Comment by Prime-AI28** [comment]
yes so the issue was resolved, there is some issue with between docker and nvidia 552.x version and later that gives this error, updating the docker desktop to v4.31 or later fixes this issue.
